### ISSUE TITLE
[Bug]: Deprecated Slack file upload method

### ISSUE THREAD

**Issue by Eddydpyl** [ComposioHQ/composio#2236]
### SDK Language

Python SDK (`composio` package)

### SDK Version

composio==0.9.4

### Runtime Environment

Python 3.11

### Environment

Production Deployment

### Steps to Reproduce

Call `slack_upload_or_create_a_file_in_slack` like so (removed values for privacy):
```json
{
  "title": "",
  "channels": "",
  "initial_comment": "",
  "content": "",
  "filename": ""
}
```
Returns the following:
```json
{
  "error": "method_deprecated",
  "ok": false,
  "response_metadata": {
    "warnings": [
      "missing_charset"
    ]
  },
  "warning": "missing_charset"
}
```
Possible culprit: https://docs.slack.dev/reference/methods/files.upload/

### Reproducibility

- [x] Always reproducible
- [ ] Intermittent / Sometimes
- [ ] Happened once, can’t reproduce

**Comment by Uday-sidagana** [comment]
Hey @Eddydpyl, thanks for flagging this! the api for this tool seems to be depreciated. We will remove it from our list of tools.

**Comment by Eddydpyl** [comment]
Thanks @Uday-sidagana is there an alternative tool? We need to be able to upload files to Slack.

**Comment by Uday-sidagana** [comment]
Hey @Eddydpyl, really sorry for the late response. Missed responding here. We've fixed the tool `slack_upload_or_create_a_file_in_slack`. Could you try and lmk if you face any issues.

**Comment by fabmont** [comment]
I have the same issue trying to upload files to Slack using this tool (`slack_upload_or_create_a_file_in_slack`). But I'm still getting the same deprecated method response. Is this really fixed already? Did the tool params changed?
